try to build for macos arm64.

diff --git a/.github/workflows/manifold.yml b/.github/workflows/manifold.yml
--- a/.github/workflows/manifold.yml
+++ b/.github/workflows/manifold.yml
@@ -5,86 +5,87 @@ name: CI
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
 on:
-  push:
-    branches: [ master, main ]
-  pull_request:
-    branches: [ master, main ]
+  workflow_dispatch:
+  # push:
+  #   branches: [ master, main ]
+  # pull_request:
+  #   branches: [ master, main ]
 
 jobs:
-  build:
-    timeout-minutes: 45
-    strategy:
-      matrix:
-        cuda_support: [OFF]
-        parallel_backend: [NONE, TBB]
-    runs-on: ubuntu-22.04
-    if: github.event.pull_request.draft == false
-    outputs:
-      java_package_version_changed: ${{ steps.check_version.outputs.changed }}
-    container:
-      image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
-    steps:
-    - name: Install dependencies
-      run: |
-        apt-get -y update
-        DEBIAN_FRONTEND=noninteractive apt install -y libomp-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev python3 python3-distutils python3-pip lcov
-        pip install trimesh
-    - uses: actions/checkout@v3
-      with:
-        submodules: recursive
-        fetch-depth: 2
-    - uses: jwlawson/actions-setup-cmake@v1.12
-    - name: Setup Java
-      uses: actions/setup-java@v2
-      with:
-        java-version: '17'
-        distribution: 'adopt'
-    - name: Install Maven
-      run: |
-        apt-get update
-        apt-get install -y maven
-    - name: Cache Maven packages
-      uses: actions/cache@v3
-      with:
-        path: ~/.m2
-        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-        restore-keys: ${{ runner.os }}-m2
-    - name: Build ${{matrix.backend}}
-      run: |
-        mkdir build
-        cd build
-        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} .. && make
-    - name: Get version
-      id: get_version
-      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
-      shell: bash
-    - name: Check if version has changed
-      id: check_version
-      shell: bash
-      run: |
-        if git diff --quiet HEAD~1 -- bindings/java/version.txt
-        then
-          echo "Version Unchanged!"
-          echo "changed=false" >> "$GITHUB_OUTPUT"
-        else
-          echo "Version Changed!"
-          echo "changed=true" >> "$GITHUB_OUTPUT"
-        fi
-    - name: Build Java package
-      shell: bash
-      run: |
-        cd bindings/java
+  # build:
+  #   timeout-minutes: 45
+  #   strategy:
+  #     matrix:
+  #       cuda_support: [OFF]
+  #       parallel_backend: [NONE, TBB]
+  #   runs-on: ubuntu-22.04
+  #   if: github.event.pull_request.draft == false
+  #   outputs:
+  #     java_package_version_changed: ${{ steps.check_version.outputs.changed }}
+  #   container:
+  #     image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
+  #   steps:
+  #   - name: Install dependencies
+  #     run: |
+  #       apt-get -y update
+  #       DEBIAN_FRONTEND=noninteractive apt install -y libomp-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev python3 python3-distutils python3-pip lcov
+  #       pip install trimesh
+  #   - uses: actions/checkout@v3
+  #     with:
+  #       submodules: recursive
+  #       fetch-depth: 2
+  #   - uses: jwlawson/actions-setup-cmake@v1.12
+  #   - name: Setup Java
+  #     uses: actions/setup-java@v2
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'adopt'
+  #   - name: Install Maven
+  #     run: |
+  #       apt-get update
+  #       apt-get install -y maven
+  #   - name: Cache Maven packages
+  #     uses: actions/cache@v3
+  #     with:
+  #       path: ~/.m2
+  #       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+  #       restore-keys: ${{ runner.os }}-m2
+  #   - name: Build ${{matrix.backend}}
+  #     run: |
+  #       mkdir build
+  #       cd build
+  #       cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} .. && make
+  #   - name: Get version
+  #     id: get_version
+  #     run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
+  #     shell: bash
+  #   - name: Check if version has changed
+  #     id: check_version
+  #     shell: bash
+  #     run: |
+  #       if git diff --quiet HEAD~1 -- bindings/java/version.txt
+  #       then
+  #         echo "Version Unchanged!"
+  #         echo "changed=false" >> "$GITHUB_OUTPUT"
+  #       else
+  #         echo "Version Changed!"
+  #         echo "changed=true" >> "$GITHUB_OUTPUT"
+  #       fi
+  #   - name: Build Java package
+  #     shell: bash
+  #     run: |
+  #       cd bindings/java
 
-        BACKEND=""
-        if [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "ON" ]; then
-            BACKEND="-cuda"
-        elif [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "OFF" ]; then
-            BACKEND=""
-        elif [ "${{matrix.cuda_support}}" = "ON" ]; then
-            BACKEND="-${{matrix.parallel_backend}}-cuda"
-        else
-            BACKEND="-${{matrix.parallel_backend}}"
-        fi
+  #       BACKEND=""
+  #       if [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "ON" ]; then
+  #           BACKEND="-cuda"
+  #       elif [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "OFF" ]; then
+  #           BACKEND=""
+  #       elif [ "${{matrix.cuda_support}}" = "ON" ]; then
+  #           BACKEND="-${{matrix.parallel_backend}}-cuda"
+  #       else
+  #           BACKEND="-${{matrix.parallel_backend}}"
+  #       fi
 
         mvn versions:set -DnewVersion=$(cat version.txt) --file pom.xml
         mvn package -Dos.classifier=linux$BACKEND-x86_64
@@ -278,6 +279,7 @@ jobs:
     strategy:
       matrix:
         parallel_backend: [NONE, TBB]
+        arch: ["aarch64"] # , "x64"]
     runs-on: macos-14
     if: github.event.pull_request.draft == false
     steps:
@@ -297,10 +299,16 @@ jobs:
     - name: Install TBB
       if: matrix.parallel_backend == 'TBB'
       run: brew install tbb
+    - name: Setup Java
+      uses: actions/setup-java@v2
+      with:
+        distribution: 'temurin' # See 'Supported distributions' for available options
+        java-version: '17'
+        architecture: ${{ matrix.arch }}
     - name: Install Java and Maven
       run: |
-        brew install openjdk@17
-        export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
+        # brew install openjdk@17
+        # export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
         brew install --ignore-dependencies maven
         echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV
     - name: Check Java version
@@ -328,7 +336,7 @@ jobs:
         JAVA_PACKAGE_VERSION=$(cat version.txt)
         echo "JAVA_PACKAGE_VERSION=$JAVA_PACKAGE_VERSION" >> $GITHUB_ENV
         mvn versions:set -DnewVersion=$JAVA_PACKAGE_VERSION --file pom.xml
-        mvn package -Dos.classifier=mac-${{matrix.parallel_backend}}-x86_64
+        mvn package -Dos.classifier=mac-${{matrix.parallel_backend}}-${{matrix.arch}}
     # - name: Test
     #   run: |
     #     cd build/test
@@ -338,16 +346,16 @@ jobs:
       with:
         name: manifold_java_bindings_mac_${{matrix.parallel_backend}}_${{env.JAVA_PACKAGE_VERSION}}
         path: bindings/java/target/*.jar
-    - name: Upload Surefire Reports
-      if: failure() # This step will run only if the previous steps failed
-      uses: actions/upload-artifact@v2
-      with:
-        name: surefire-reports
-        path: |
-          /Users/runner/work/manifold/manifold/bindings/java/target/surefire-reports
-          /Users/runner/work/manifold/manifold/bindings/java/target/*.dump
-          /Users/runner/work/manifold/manifold/bindings/java/target/*-jvmRun*.dump
-          /Users/runner/work/manifold/manifold/bindings/java/target/*.dumpstream
+    # - name: Upload Surefire Reports
+    #   if: failure() # This step will run only if the previous steps failed
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: surefire-reports
+    #     path: |
+    #       /Users/runner/work/manifold/manifold/bindings/java/target/surefire-reports
+    #       /Users/runner/work/manifold/manifold/bindings/java/target/*.dump
+    #       /Users/runner/work/manifold/manifold/bindings/java/target/*-jvmRun*.dump
+    #       /Users/runner/work/manifold/manifold/bindings/java/target/*.dumpstream
 
   # build_nix:
   #   timeout-minutes: 30
@@ -363,67 +371,67 @@ jobs:
   #   - uses: cachix/install-nix-action@v15
   #   - run: nix build -L '.?submodules=1#manifold-${{matrix.variant}}'
 
-  deploy_jars:
-    runs-on: ubuntu-22.04
-    needs: [build, build_mac]
-    if: github.event.pull_request.draft == false && ${{needs.build.outputs.java_package_version_changed}} == 'true'
-    steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
-      with:
-        submodules: recursive
-        fetch-depth: 2
-    - name: Set up JDK 17
-      uses: actions/setup-java@v2
-      with:
-        java-version: '17'
-        distribution: 'adopt'
-    - name: Install Maven
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y maven
-    - name: Get version
-      id: get_version
-      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
-      shell: bash
-    - name: Download Artifacts
-      uses: actions/download-artifact@v2
-      with:
-        name: manifold_java_bindings_linux_NONE_OFF_${{env.VERSION}}
-        path: linux-jar
-    - name: Download Artifacts
-      uses: actions/download-artifact@v2
-      with:
-        name: manifold_java_bindings_mac_TBB_${{env.VERSION}}
-        path: mac-tbb-jar
-    - name: Download Artifacts
-      uses: actions/download-artifact@v2
-      with:
-        name: manifold_java_bindings_linux_TBB_OFF_${{env.VERSION}}
-        path: linux-tbb-jar
-    - name: Deploy Jars
-      shell: bash
-      run: |
-        VERSION=$(cat bindings/java/version.txt)
-        linux_jar_file=linux-jar/manifold3d-$VERSION-linux-x86_64.jar
-        linux_tbb_jar_file=linux-tbb-jar/manifold3d-$VERSION-linux-TBB-x86_64.jar
-        mac_tbb_jar_file=mac-tbb-jar/manifold3d-$VERSION-mac-TBB-x86_64.jar
+  # deploy_jars:
+  #   runs-on: ubuntu-22.04
+  #   needs: [build, build_mac]
+  #   if: github.event.pull_request.draft == false && ${{needs.build.outputs.java_package_version_changed}} == 'true'
+  #   steps:
+  #   - name: Checkout Code
+  #     uses: actions/checkout@v3
+  #     with:
+  #       submodules: recursive
+  #       fetch-depth: 2
+  #   - name: Set up JDK 17
+  #     uses: actions/setup-java@v2
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'adopt'
+  #   - name: Install Maven
+  #     run: |
+  #       sudo apt-get update
+  #       sudo apt-get install -y maven
+  #   - name: Get version
+  #     id: get_version
+  #     run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
+  #     shell: bash
+  #   - name: Download Artifacts
+  #     uses: actions/download-artifact@v2
+  #     with:
+  #       name: manifold_java_bindings_linux_NONE_OFF_${{env.VERSION}}
+  #       path: linux-jar
+  #   - name: Download Artifacts
+  #     uses: actions/download-artifact@v2
+  #     with:
+  #       name: manifold_java_bindings_mac_TBB_${{env.VERSION}}
+  #       path: mac-tbb-jar
+  #   - name: Download Artifacts
+  #     uses: actions/download-artifact@v2
+  #     with:
+  #       name: manifold_java_bindings_linux_TBB_OFF_${{env.VERSION}}
+  #       path: linux-tbb-jar
+  #   - name: Deploy Jars
+  #     shell: bash
+  #     run: |
+  #       VERSION=$(cat bindings/java/version.txt)
+  #       linux_jar_file=linux-jar/manifold3d-$VERSION-linux-x86_64.jar
+  #       linux_tbb_jar_file=linux-tbb-jar/manifold3d-$VERSION-linux-TBB-x86_64.jar
+  #       mac_tbb_jar_file=mac-tbb-jar/manifold3d-$VERSION-mac-TBB-x86_64.jar
 
-        mvn versions:set -DnewVersion=$VERSION --file bindings/java/pom.xml
-        mvn deploy:deploy-file \
-          -DpomFile=bindings/java/pom.xml \
-          -DrepositoryId=clojars \
-          -Durl=https://clojars.org/repo \
-          -DgroupId=org.clojars.cartesiantheatrics \
-          -DartifactId=manifold3d \
-          -Dversion=$VERSION \
-          -Dpackaging=jar \
-          -Dfile=$linux_tbb_jar_file \
-          -Dclassifier=linux-TBB-x86_64 \
-          -Dfiles=$mac_tbb_jar_file,$linux_jar_file \
-          -Dclassifiers=mac-TBB-x86_64,linux-x86_64 \
-          -Dtypes=jar,jar \
-          --settings=bindings/java/settings.xml
-      env:
-        CLOJARS_PASSPHRASE: ${{ secrets.CLOJARS_PASSPHRASE }}
-        CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
+  #       mvn versions:set -DnewVersion=$VERSION --file bindings/java/pom.xml
+  #       mvn deploy:deploy-file \
+  #         -DpomFile=bindings/java/pom.xml \
+  #         -DrepositoryId=clojars \
+  #         -Durl=https://clojars.org/repo \
+  #         -DgroupId=org.clojars.cartesiantheatrics \
+  #         -DartifactId=manifold3d \
+  #         -Dversion=$VERSION \
+  #         -Dpackaging=jar \
+  #         -Dfile=$linux_tbb_jar_file \
+  #         -Dclassifier=linux-TBB-x86_64 \
+  #         -Dfiles=$mac_tbb_jar_file,$linux_jar_file \
+  #         -Dclassifiers=mac-TBB-x86_64,linux-x86_64 \
+  #         -Dtypes=jar,jar \
+  #         --settings=bindings/java/settings.xml
+  #     env:
+  #       CLOJARS_PASSPHRASE: ${{ secrets.CLOJARS_PASSPHRASE }}
+  #       CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
